---
- name: Configure webserver with nginx
  hosts: webservers
  sudo: True
  tasks:
    - name: install epel
      yum: name=epel-release update_cache=yes
    - name: install nginx
      yum: name=nginx update_cache=yes
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/conf.d
   # - name: enable configuration
   #   file: >
   #     dest=/etc/nginx/sites-enabled/default
   #     src=/etc/nginx/sites-available/default
   #     state=link
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
    - name: restart nginx
      service: name=nginx state=restarted
