---
- name: Configure webserver with nginx and tls
  hosts: webservers
  sudo: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/ssl.conf
    server_name: localhost
  tasks:
    - name: Install nginx
      yum: name=nginx update_cache=yes
    - name: Add user
      user: name=nginx shell=/sbin/nologin home=/run/nginx
    - name: create TLS directories
      file: path=/etc/nginx/ssl state=directory
    - name: create directories for nginx
      file: path=/etc/nginx/conf.d state=directory 
    - name: copy TLS key
      copy: src=key/nginx.key dest={{ key_file }} owner=nginx mode=0600
      notify: restart nginx
    - name: copy TLS certificate
      copy: src=key/nginx.crt dest={{ cert_file }} owner=nginx mode=0600
      notify: restart nginx
    - name: copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
