#playbook head begin
---
- 
  name: Install Mongodb
  hosts: webservers
  sudo: True
  vars:
    mongodb:
      dbpath: /var/lib/mongo/
  tasks:
#playbook head end
    - name: add Mongodb Offical repo
      template: src=repo.j2 dest=/etc/yum.repos.d/mongodb.repo
      tags: mongodb

    - name: install mongodb
      yum: name=mongodb-org-server state=present
      tags: mongodb

    - name: configure mongodb
      template: src=mongod.conf.j2 dest=/etc/mongod.conf
      tags: mongodb

    - name: run mongodb
      service: name=mongod state=started enabled=yes
      tags: mongodb
